# SwiftLint Configuration for SimpleTimesheet
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - Sources
  - SimpleTimesheet
  - SimpleTimesheetMac
  - SimpleTimesheetWidget
  - Tests

# Paths to exclude
excluded:
  - .build
  - DerivedData
  - Android
  - Pods
  - Packages

# Enabled rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo  # Allow TODO comments during development
  - trailing_whitespace  # Can be noisy
  - line_length  # Handled separately below
  - identifier_name  # SwiftUI uses short names like 'id'

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - to

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 60

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use os_log or Logger instead of print() in production code"
    severity: warning
    excluded: ".*Tests\\.swift"
